### ISSUE TITLE
Document `SYMFONY_FORCE_TUNNEL_ENVS_MASTER`

### ISSUE THREAD

**Issue by fabpot** [symfonycorp/symfony-cloud-docs#1]
I've not done it as it's not clear where to put that information for now. We might need a new cookbook about using SC locally (with the local web server for instance) or create a tunnel cookbook.

**Comment by OskarStark** [comment]
I had exactly same problem on my first initial setup. One more thing is, that most new setups are done on master without branches until it’s running at some state. Having different behavior for master and all other branches is not easy to get.

**Comment by tucksaun** [comment]
`SYMFONY_FORCE_TUNNEL_ENVS_MASTER` does not exist anymore, it has been replaced by the ``--expose-env-vars`` on ``tunnel:open`` instead.
