### ISSUE TITLE
How can I change the project title?

### ISSUE THREAD

**Issue by OskarStark** [symfonycorp/symfony-cloud-docs#141]
I searched the docs, but didn't find anything.

How can I change the project title?
![CleanShot 2021-01-06 at 15 31 59](https://user-images.githubusercontent.com/995707/103779743-723c2d80-5034-11eb-8156-072a314a4cca.png)

**Comment by OskarStark** [comment]
Found it thanks to Titouan:
`symfony project:rename Foo`

**Comment by fabpot** [comment]
Closing then.
