### ISSUE TITLE
Which regions (availability zones and countries like EU (UK, Austria), US, China) are supported by SymfonyCloud?

### ISSUE THREAD

**Issue by Antarian** [symfonycorp/symfony-cloud-docs#153]
I am trying to find out information about regions and it is nowhere available. I am starting to suspect that this service is probably available only in one location which I was able to find EU-WEST? And also in what countries are servers in for this EU-WEST , is it UK, Germany, France etc.?

**Comment by petitj** [comment]
I just got the answer from the support team. For now it's only in eu-west-1 AWS datacenter (Europe (Ireland)).

**Comment by fabpot** [comment]
Many more regions are coming soon (by the end of the year).
