### ISSUE TITLE
Wrong message and version is shown

### ISSUE THREAD

**Issue by OskarStark** [symfonycorp/symfony-cloud-docs#19]
This is probably because its rendered within the Symfony docs where `master` is `5.0`... 🤔 

cc @javiereguiluz  

<img width="1284" alt="Screenshot 2019-08-21 08 55 04" src="https://user-images.githubusercontent.com/995707/63409445-7a6cdc00-c3f1-11e9-85a7-c6e896f47810.png">

**Comment by fabpot** [comment]
This was a bug on all docs, fixed now.
