### ISSUE TITLE
How can I determine which kind of environment I am deploying to?

### ISSUE THREAD

**Issue by localheinz** [symfonycorp/symfony-cloud-docs#81]
When configuring the `build` hook in `.symfony.cloud.yaml`, we currently do not know which environment we deploy too.

Consequently, we deploy the same assets to development and production environments. 

For example, when we deploy to a production environment, all development dependencies are installed with `composer`. 

Similarly, we run 

```
$ yarn run build
```

which builds our frontend assets with `webpack`, but we currently deploy the same large files into  production that we deploy to development.

How can we determine which environment we deploy too?

I have run

```
$ env | sort
```

in the `build` hook to list all declared environment variables, but I have not found an indication for an environment variable, such as `APP_ENV`, that could help me take a different path building the application/

How can we determine which environment we are deploying to?

Shall we use `git` to determine the branch name?

**Comment by localheinz** [comment]
For the record, running

```
$ git rev-parse --abbrev-ref HEAD
```
fails with

```
W: fatal: Not a git repository (or any parent up to mount point /app)
W: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by tucksaun** [comment]
Builds are independent of the environment context so this is not possible.

**Comment by localheinz** [comment]
@tucksaun 

So I need to run these steps during the `deploy` hook instead?

**Comment by localheinz** [comment]
@tucksaun 

So how are we supposed to properly build an application for a production environment when we do not know which environment we are currently building for?

**Comment by localheinz** [comment]
@tucksaun 

For example, when taking a look at the corresponding [`platform.sh` documentation](https://docs.platform.sh/configuration/app/build.html#how-can-i-run-certain-commands-only-on-certain-environments), it appears that `platform.sh` makes a [range of environment variables](https://docs.platform.sh/development/variables.html#platformsh-provided-variables) available, such as `PLATFORM_BRANCH`.

I think it would only be sensible to expose the `SYMFONY_BRANCH` environment variable at the same time.

As mentioned earlier, I ran

```
$ env | sort
```

in the `build` hook, but there are no environment variables available with the `PLATFORM_` prefix. 

Also, only the following environment variables with the `SYMFONY_` prefix are available:

- `SYMFONY_APPLICATION`
- `SYMFONY_APPLICATION_NAME`
- `SYMFONY_APP_DIR`
- `SYMFONY_CACHE_DIR`
- `SYMFONY_DIR`
- `SYMFONY_DOCUMENT_ROOT`
- `SYMFONY_OUTPUT_DIR`
- `SYMFONY_PROJECT`
- `SYMFONY_PROJECT_ENTROPY`
- `SYMFONY_SOURCE_DIR`
- `SYMFONY_TOKEN`
- `SYMFONY_TREE_ID`
- `SYMFONY_VARIABLES`

What is keeping you from exposing the `SYMFONY_BRANCH` environment variable?

Based on its content, we could easily determine the target environment, and properly build assets for that specific environment.

**Comment by tucksaun** [comment]
@localheinz they don't exist for the build stage. see:
> The following variables exist only at runtime. If used in a build hook they will evaluate to an empty string like any other unset variable:
> - PLATFORM_BRANCH: The name of the Git branch.
> - ...

Because it applies the "Build once, Run anywhere". The same applies to SymfonyCloud.
Container images are built once and they deployed to different environments: this result in idempotent images that are known to work before deployment.

Depending on your application you have several choices:
- build a production and development assets during the build and select which one to point at runtime
- build a single asset release and configure it from outside (if you need to change and endpoint for example)
- define a variable inside the `.symfony.cloud.yaml` and change it based on your own logic.

**Comment by localheinz** [comment]
@tucksaun 

Ha, I misread, thanks!
